const express = require('express')
const adminRoute = express.Router()
const {addCategory, handleAdminLogin, dashboard, usersList, updateUserStatus, tutorsList, updateTutorStatus, tutorViewAndApprove, getCourse, courseViewAndApprove,courseManage, getTransctions, adminAuthentication } = require('../controllers/adminController')
const { adminAuth } = require('../middlewares/adminAuth')
const {getCouponsData, createCoupon, deleteCourse} = require('../controllers/couponController')

adminRoute.post('/', handleAdminLogin)
adminRoute.get('/auth', adminAuth,adminAuthentication)
adminRoute.get('/dashboard',adminAuth, dashboard)
adminRoute.get('/users',adminAuth, usersList)
adminRoute.patch('/user/status',adminAuth, updateUserStatus)
adminRoute.get('/tutors',adminAuth, tutorsList)
adminRoute.patch('/tutor/status',adminAuth, updateTutorStatus)
adminRoute.post('/tutor/view',adminAuth, tutorViewAndApprove)
adminRoute.get('/courses',adminAuth, getCourse)
adminRoute.post('/course/view',adminAuth, courseViewAndApprove)
adminRoute.post('/course/manage',adminAuth, courseManage)
adminRoute.post('/category',adminAuth, addCategory)
adminRoute.get('/coupons',adminAuth,getCouponsData)
adminRoute.get('/transctions',adminAuth,getTransctions)
adminRoute.post('/coupons',adminAuth, createCoupon)
adminRoute.delete('/coupon/delete/:couponId',adminAuth, deleteCourse)

module.exports = adminRoute